version: 1.2
    workflows:
        - subclass: <CWL | WDL | NFL | GALAXY>
          primaryDescriptorPath: <String>  # absolute path
          testParameterFiles: <String Array>  # absolute path
          readMePath: <String> # absolute path
          authors:
              - name: <String>
                email: <String>
          
